### ISSUE TITLE
Feature: Login as User

### ISSUE THREAD

**Issue by Bob-Loth** [Bob-Loth/csc-307#3]
register button and page - g

**Comment by david-1-nguyen** [comment]
> _No description provided._

**Comment by Bob-Loth** [comment]
- [ ] login, check hash, redirect - Bob

- [ ] register users to database - David

- [ ] create utility folder in backend - Gennady

**Comment by Bob-Loth** [comment]
Redirects done by Gennady, I'll take registering, and should have it finished by the time we meet tomorrow.

**Comment by Bob-Loth** [comment]
Users can use the register button to redirect to a register page, enter their credentials, and be added to the database.
Users can login using their credentials to be redirected to a (to be constructed) dashboard.

**Comment by david-1-nguyen** [comment]
Added Navigation Bar component

**Comment by Bob-Loth** [comment]
- [ ] Harden Login component by implementing JWT tokens.
     Stored on database and local storage, users should only be able to access protected pages if they are logged in.

- [ ] Display error messages on failed login/register attempts.

Moved these sub-issues to Milestone 2.

**Comment by david-1-nguyen** [comment]
Refactored login and registration to always return errors dictionary, changed errors dictionary so that username and password hold an array of errors individually, fixed the login page to correctly map out new username and password errors.

**Comment by david-1-nguyen** [comment]
Big changes: implemented backend to create and send jwt token when login in. Frontend handles stores jwt token, accesses it through useContext(AuthContext) whenever it needs to do anything regarding finding out the user, logging in, and logging out. Refactored Menubar to change depending if user is logged in or not. Made authenticated routes so that if non users try to access a route without a jwt token, they're redirected back to login.
What's left: 
- Backend routes like search and dashboard will send 400 error if user jwt token isn't authenticated or correct
